# db/seeds/schools.rb

schools = [
  { name: 'Amherst College', undergraduate: true, mba: false, other_graduate: false, other: false },
  { name: 'Harvard University', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Harvard Business School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Stanford University', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Stanford Graduate School of Business', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Yale University', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Yale School of Management', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Princeton University', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Columbia University', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Columbia Business School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Chicago', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Booth School of Business', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Massachusetts Institute of Technology (MIT)', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'MIT Sloan School of Management', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Pennsylvania', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Wharton School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Dartmouth College', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Tuck School of Business', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Northwestern University', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Kellogg School of Management', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Oxford', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Saïd Business School (Oxford)', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Cambridge', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Judge Business School (Cambridge)', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'London Business School (LBS)', undergraduate: false, mba: true, other_graduate: true, other: false },
  { name: 'Indian Institute of Technology (IIT)', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Indian Institute of Management Ahmedabad (IIM Ahmedabad)', undergraduate: false, mba: true, other_graduate: true, other: false },
  { name: 'Indian Institute of Management Bangalore (IIM Bangalore)', undergraduate: false, mba: true, other_graduate: true, other: false },
  { name: 'Indian Institute of Management Calcutta (IIM Calcutta)', undergraduate: false, mba: true, other_graduate: true, other: false },
  { name: 'Indian School of Business (ISB)', undergraduate: false, mba: true, other_graduate: true, other: false },
  { name: 'HEC Paris', undergraduate: false, mba: true, other_graduate: true, other: false },
  { name: 'INSEAD', undergraduate: false, mba: true, other_graduate: true, other: false },
  { name: 'University of London', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'University of Toronto', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Rotman School of Management', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Melbourne', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Melbourne Business School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Sydney', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Australian Graduate School of Management', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'National University of Singapore (NUS)', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'NUS Business School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Hong Kong', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'HKU Business School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Seoul National University', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'KAIST Business School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of Tokyo', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Tokyo Business School', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'University of British Columbia', undergraduate: true, mba: false, other_graduate: true, other: false },
  { name: 'Sauder School of Business', undergraduate: false, mba: true, other_graduate: false, other: false },
  { name: 'Other', undergraduate: true, mba: true, other_graduate: true, other: true }
]

School.create!(schools)

